FWCOMMANDS = [

  {:id => 0x42, :name => "ENTER_BOOTLOADER"},
  {:id => 0x5A, :name => "NO_OPERATION"},
  {:id => 0x76, :name => "FIRMWARE_VERSION"},
  {:id => 0xA0, :name => "SETVDD", :dataLength => 3},
  {:id => 0xA1, :name => "SETVPP", :dataLength => 3},
  {:id => 0xA2, :name => "READ_STATUS"},
  {:id => 0xA3, :name => "READ_VOLTAGES"},
  {:id => 0xA4, :name => "DOWNLOAD_SCRIPT", :dataLength => 2, :switchToScript => true},
  {:id => 0xA5, :name => "RUN_SCRIPT", :dataLength => 2},
  {:id => 0xa6, :name => "EXECUTE_SCRIPT", :dataLength => 1, :switchToScript => true},
  {:id => 0xA7, :name => "CLR_DOWNLOAD_BUFFER"},
  {:id => 0xA8, :name => "DOWNLOAD_DATA", :dataLength => 1, :dumpData => true},
  {:id => 0xA9, :name => "CLR_UPLOAD_BUFFER"},
  {:id => 0xAA, :name => "UPLOAD_DATA"},
  {:id => 0xAB, :name => "CLR_SCRIPT_BUFFER"},
  {:id => 0xAC, :name => "UPLOAD_DATA_NOLEN"},
  {:id => 0xad, :name => "END_OF_BUFFER", :isLast => true},
  {:id => 0xAE, :name => "RESET", :isLast => true},
  {:id => 0xAF, :name => "SCRIPT_BUFFER_CHKSM"},
  {:id => 0xB0, :name => "SET_VOLTAGE_CALS", :dataLength => 4},
  {:id => 0xB1, :name => "WR_INTERNAL_EE", :dataLength => 2, :dumpData => true},
  {:id => 0xB2, :name => "RD_INTERNAL_EE", :dataLength => 2},
  {:id => 0xB3, :name => "ENTER_UART_MODE", :dataLength => 2},
  {:id => 0xB4, :name => "EXIT_UART_MODE"},
  {:id => 0xB5, :name => "ENTER_LEARN_MODE", :dataLength => 4},
  {:id => 0xB6, :name => "EXIT_LEARN_MODE"},
  {:id => 0xB7, :name => "ENABLE_PK2GO_MODE", :dataLength => 4},
  {:id => 0xB8, :name => "LOGIC_ANALYZER_GO", :dataLength => 8},
  {:id => 0xB9, :name => "COPY_RAM_UPLOAD", :dataLength => 2},
  {:id => 0x80, :name => "READ_OSCCAL", :dataLength => 2},
  {:id => 0x81, :name => "WRITE_OSCCAL", :dataLength => 2},
  {:id => 0x82, :name => "START_CHECKSUM", :dataLength => 2},
  {:id => 0x83, :name => "VERIFY_CHECKSUM", :dataLength => 2},
  {:id => 0x84, :name => "CHECK_DEVICE_ID", :dataLength => 4},
  {:id => 0x85, :name => "READ_BANDGAP"},
  {:id => 0x86, :name => "WRITE_CFG_BANDGAP"},
  {:id => 0x87, :name => "CHANGE_CHKSM_FRMT", :dataLength => 2},

]
